### ISSUE TITLE
When code open-source?

### ISSUE THREAD

**Issue by harrylin-hyl** [OpenVisualLab/NexusAD#1]

**Comment by 2-mo** [comment]
I’ve been busy with my thesis proposal recently. After it’s done, I plan to clean up the code and improve it before the end of this semester. Rest assured, it will definitely be open-sourced.

**Comment by sgzqc** [comment]
Looking Forward to the Open Source Code....

**Comment by 2-mo** [comment]
> Looking Forward to the Open Source Code....

Thank you very much for your attention to our code! 🙌 As I mentioned earlier, I planned to update the code after my thesis proposal defense, which is happening this afternoon. 🎓 I’ll dive into the updates right after. 🧑‍💻

**Comment by sgzqc** [comment]
Wishing you all the best!

**Comment by sgzqc** [comment]
Hi, Everything going smoothly? When is it expected to be open-sourced?

**Comment by 2-mo** [comment]
> Hi, Everything going smoothly? When is it expected to be open-sourced?

Thank you for your attention. I have uploaded the unorganized files in [[250113]Unorganized.](https://github.com/OpenVisualLab/NexusAD/tree/main/%5B250113%5DUnorganized) You can ask questions anytime, and I will do my best to respond promptly. However, due to some unexpected matters recently, it has been difficult for me to focus on handling the code. I hope you can understand. Thank you again.
